[temperature_automation.thermostat]
# want faster target but more overshoot? Try Kp=0.035, Ki=0.0, Kd=11.0
Kp=0.035
Ki=0.0
Kd=11.0

[ui.overview.charts]
temperature=1


[temperature_automation]
# MLX90632 I2C address
mlx_address=0x3A
# sensor/inference period in seconds
sample_period_s=1.0
