[temperature_automation.thermostat]
Kp=0.03
Ki=0.0
Kd=12.0

[ui.overview.charts]
temperature=1


[temperature_automation]
# MLX90632 I2C address
mlx_address=0x3A
# sensor/inference period in seconds
sample_period_s=1.0
